Repository Team-Bloblow/Bloblow-Client, pull requests merged in 2024-12, with the labels that each got.

#59 Feat: 최근 업데이트 그룹의 키워드별 게시물 수 조회 UI 구현
  src/api/group/asyncGet GroupSummary.js
  src/components/Card/UserGroup/UserGroupCard.jsx
  src/components/Card/UserGroup/UserGroupCardList.jsx
  src/components/Sidebar/GroupSummary.jsx
  src/components/Sidebar/MyPageSidebar.jsx
  src/pages/GroupPage.jsx
  src/utils/getDateDiff.js
Labels: ✨ feat, 📣 code review

#60 Fix: scrollY가 0이상일 경우, layout shift가 일어나는 현상 디버깅
  src/hooks/useScrollDisable.js
Labels: ✏ fix

#62 Improve: 온보딩 UX 개선
  src/api/group/asyncPostGroup.js
  src/components/Card/UserGroup/UserGroupCardList.jsx
  src/components/Modal/CreateGroupModal.jsx
  src/components/Modal/CreateKeywordModal.jsx
  src/components/Modal/CreateKeywordSuccessModal.jsx
  src/components/Pagination/GroupPeriodPagination.jsx
  src/components/Sidebar/DashboardSidebar.jsx
  src/components/Sidebar/GroupSummary.jsx
  src/components/Sidebar/MyPageSidebar.jsx
  src/config/constants.js
Labels: ✨ feat, 🎨 style, 📣 code review, 🔨 refactor

#63 Feat: 수동 크롤링 구현
  src/api/crawl/asyncPostKeywords.js
  src/components/Button/StartCrawlingButton.jsx
  src/components/Card/Post/PostCardList.jsx
  src/components/Header/DashboardHeader.jsx
  src/components/Modal/CreateKeywordModal.jsx
Labels: ✏ fix, ✨ feat, 🎨 style, 📣 code review

#54 Docs: 리드미 템플릿 작성
  README.md
  public/assets/3-1-1.png
  public/assets/3-1-2.png
  public/assets/4-1-1.png
  public/assets/bloblow_green_crop.png
  public/assets/bloblow_tech_stack.png
  public/assets/docs-preview-group.png
  public/assets/docs-preview-home.png
  public/assets/docs-preview-keyword-chart.png
  public/assets/docs-preview-post-list.png
Labels: 📃 docs, 📣 code review

#67 [Fix: 파일명 수정] 파일명에 공백이 있어서 파일명 수정
  src/api/group/asyncGetGroupSummary.js
  src/components/Sidebar/GroupSummary.jsx
Labels: ✏ fix, 🐛 bug

#68 Fix: 무한 스크롤이 작동되지 않고 한번에 모든 데이터 불러와지는 이슈 해결
  src/components/Card/Post/PostCardList.jsx
  src/components/Card/Post/PostListFilter.jsx
  src/hooks/useInfiniteData.js
Labels: ✏ fix, 📣 code review

#72 Docs: Readme 업데이트
  README.md
Labels: 📃 docs

#73 Merge: Dev branch to Main
  README.md
  src/api/group/asyncGetGroupSummary.js
  src/components/Card/Post/PostCardList.jsx
  src/components/Card/Post/PostListFilter.jsx
  src/components/Sidebar/GroupSummary.jsx
  src/hooks/useInfiniteData.js
Labels: ⚙ chore, ✏ fix, ✨ feat, 🎨 style, 📃 docs

#69 Feat: 로그인 인증 상태 지속성 local 기준 적용
  src/components/Button/SignInButton.jsx
  src/components/Layout/Header.jsx
  src/pages/App.jsx
Labels: ✨ feat, 📣 code review

#71 Feat: 모든 페이지에 대한 반응형 디자인 구현
  src/components/Button/CreateKeywordButton.jsx
  src/components/Button/PeriodToggleButton.jsx
  src/components/Button/SignInButton.jsx
  src/components/Card/Chart/GroupPeriodPostCountCard.jsx
  src/components/Card/Chart/PeriodAdCountCard.jsx
  src/components/Card/Chart/PeriodPostCountCard.jsx
  src/components/Card/Chart/PeriodReactionCountCard.jsx
  src/components/Card/Chart/TodayPostCountCard.jsx
  src/components/Card/Post/PostCard.jsx
  src/components/Card/Post/PostListFilter.jsx
  src/components/Card/UserGroup/UserGroupCard.jsx
  src/components/Card/UserGroup/UserGroupCardList.jsx
  src/components/Chart/GroupLineChart.jsx
  src/components/Chart/LineChart.jsx
  src/components/Chart/MultiTypeChart.jsx
  src/components/Chart/StackBarChart.jsx
  src/components/Header/DashboardHeader.jsx
  src/components/Icon/ClickIcon.jsx
  src/components/Layout/Footer.jsx
  src/components/Layout/Header.jsx
  src/components/Modal/AlertModal.jsx
  src/components/Modal/ConfirmModal.jsx
  src/components/Modal/CreateGroupModal.jsx
  src/components/Modal/CreateKeywordModal.jsx
  src/components/Modal/CreateKeywordSuccessModal.jsx
  src/components/Modal/ErrorModal.jsx
  src/components/Modal/ModalFrame.jsx
  src/components/Pagination/GroupPeriodPagination.jsx
  src/components/Pagination/PeriodPagination.jsx
  src/components/Sidebar/DashboardSidebar.jsx
  src/components/Sidebar/GroupSummary.jsx
  src/components/Sidebar/MyPageSidebar.jsx
  src/hooks/useDropDown.js
  src/hooks/useViewportSize.js
  src/pages/App.jsx
  src/pages/GroupPage.jsx
  src/pages/HomePage.jsx
  src/pages/KeywordPage.jsx
  src/pages/MyPage.jsx
  src/store/client/authSlice.js
  src/utils/throttle.js
Labels: ✨ feat, 🎨 style, 📣 code review
