Repository Team-Bloblow/Bloblow-Client, pull requests merged in 2024-11, with the labels that each got.

#4 Feat: 보일러 플레이트 세팅
  .github/ISSUE_TEMPLATE/feature.yml
  .github/pull_request_template.md
  .husky/pre-commit
  .prettierignore
  .prettierrc
  eslint.config.js
  index.html
  package-lock.json
  package.json
  postcss.config.js
  public/favicon.png
  public/vite.svg
  src/App.css
  src/App.jsx
  src/assets/react.svg
  src/config/ReactQueryProvider.jsx
  src/config/globals.css
  src/index.css
  src/main.jsx
  src/pages/App.jsx
  src/pages/GroupPage.jsx
  src/pages/HomePage.jsx
  src/pages/KeywordPage.jsx
  src/pages/MyPage.jsx
  src/store/client/useBoundStore.js
  tailwind.config.js
  vite.config.js
Labels: ⚙ chore, ✨ feat, 📃 docs

#5 Feat: 로그인 버튼 및 로그인 관련 로직 구현
  package-lock.json
  package.json
  src/api/auth/asyncPostSignIn.js
  src/api/index.js
  src/components/Button/SignInButton.jsx
  src/components/Layout/Header.jsx
  src/components/Logo.jsx
  src/components/UI/Button.jsx
  src/config/firebase.js
  src/hooks/useNoSignInRedirect.js
  src/pages/App.jsx
  src/pages/HomePage.jsx
  src/pages/MyPage.jsx
  src/store/client/authSlice.js
  src/store/client/useBoundStore.js
  tailwind.config.js
  vite.config.js
Labels: ✨ feat, 🎨 style, 📣 code review

#7 Feat: 키워드 생성 모달 UI 구현
  index.html
  src/components/Button/CreateKeywordButton.jsx
  src/components/Button/SignInButton.jsx
  src/components/Common/Logo.jsx
  src/components/Common/Portal.jsx
  src/components/DropDown/SelectGroupDropDown.jsx
  src/components/DropDown/SelectGroupOptionList.jsx
  src/components/Icon/CloseIcon.jsx
  src/components/Icon/PlusIcon.jsx
  src/components/Icon/ProfileIcon.jsx
  src/components/Icon/TriangleDownIcon.jsx
  src/components/Icon/TriangleUpIcon.jsx
  src/components/Layout/Footer.jsx
  src/components/Layout/Header.jsx
  src/components/Logo.jsx
  src/components/Modal/CreateKeywordModal.jsx
  src/components/Modal/ModalBackground.jsx
  src/components/Modal/ModalFrame.jsx
  src/components/Sidebar/MyPageSidebar.jsx
  src/components/UI/Button.jsx
  src/components/UI/Label.jsx
  src/config/const.js
  src/config/globals.css
  src/hooks/useDropDown.js
  src/hooks/useScrollDisable.js
  src/hooks/useSignInRedirect.js
  src/pages/HomePage.jsx
  src/pages/MyPage.jsx
  src/store/client/authSlice.js
  src/store/client/modalSlice.js
  src/store/client/useBoundStore.js
  tailwind.config.js
Labels: ✨ feat, 🎨 style, 📣 code review

#9 Fix: 파일 경로 변경으로 인한 import 상대 경로 관련 에러 및 mountDomNode 타입 에러 해결
  src/components/Common/Logo.jsx
  src/components/Common/Portal.jsx
Labels: ✏ fix, 🔨 refactor

#13 Feat: 서버 API와의 연결 및 로직/에러핸들링 최적화 (무한스크롤, 로그인, 유저 그룹 리스트, 키워드 등록)
  src/api/group/asyncGetUserGroup.js
  src/api/post/asyncGetPosts.js
  src/components/Button/SignInButton.jsx
  src/components/Card/Post/PostCard.jsx
  src/components/Card/Post/PostCardList.jsx
  src/components/Card/UserGroup/UserGroupCard.jsx
  src/components/Card/UserGroup/UserGroupCardList.jsx
  src/components/Chip/KeywordChip.jsx
  src/components/DropDown/SelectGroupDropDown.jsx
  src/components/DropDown/SelectGroupOptionList.jsx
  src/components/Header/DashboardHeader.jsx
  src/components/Icon/ProfileIcon.jsx
  src/components/Modal/CreateKeywordModal.jsx
  src/components/Sidebar/DashboardSidebar.jsx
  src/components/Sidebar/MyPageSidebar.jsx
  src/components/UI/Error.jsx
  src/components/UI/Loading.jsx
  src/config/constants.js
  src/hooks/useInfiniteData.js
  src/hooks/useNoSignInRedirect.js
  src/hooks/useObserver.js
  src/pages/GroupPage.jsx
  src/pages/KeywordPage.jsx
  src/pages/MyPage.jsx
  src/store/client/authSlice.js
  src/store/client/userDataSlice.js
  tailwind.config.js
Labels: ✏ fix, ✨ feat, 🎨 style, 📣 code review, 🔨 refactor

#18 Feat: 대시보드의 사이드바와 헤더 UI 및 로직 구현
  src/api/keyword/asyncGetKeyword.js
  src/components/Card/Post/PostCard.jsx
  src/components/Card/Post/PostCardList.jsx
  src/components/Card/UserGroup/UserGroupCard.jsx
  src/components/Card/UserGroup/UserGroupCardList.jsx
  src/components/Chip/AdChip.jsx
  src/components/Chip/KeywordChip.jsx
  src/components/Header/DashboardHeader.jsx
  src/components/Icon/EditIcon.jsx
  src/components/Icon/ExclamationMarkIcon.jsx
  src/components/Icon/LinkIcon.jsx
  src/components/Icon/MinusCircleIcon.jsx
  src/components/Icon/PlusCircleIcon.jsx
  src/components/Icon/PlusSquareIcon.jsx
  src/components/Icon/RevertIcon.jsx
  src/components/Layout/Header.jsx
  src/components/Modal/CreateKeywordModal.jsx
  src/components/Sidebar/DashboardSidebar.jsx
  src/components/Sidebar/MyPageSidebar.jsx
  src/config/constants.js
  src/pages/GroupPage.jsx
  src/pages/KeywordPage.jsx
Labels: ✨ feat, 🎨 style

#22 Feat: 키워드 대시보드 내 오늘의 게시물 차트 및 주간 게시물 차트 UI 구현
  package-lock.json
  package.json
  src/api/keyword/asyncGetPostCountList.js
  src/api/keyword/asyncGetTodayPostCount.js
  src/components/Card/Chart/PeriodPostCountCard.jsx
  src/components/Card/Chart/TodayPostCountCard.jsx
  src/components/Chart/LineChart.jsx
  src/components/Icon/LeftCarouselIcon.jsx
  src/components/Icon/RightCarouselIcon.jsx
  src/components/Pagination/PeriodPagination.jsx
  src/config/constants.js
  src/pages/KeywordPage.jsx
  src/utils/date.js
Labels: ✨ feat, 📣 code review

#23 Style: 전체 UI 수정
  .github/pull_request_template.md
  src/components/Button/CreateKeywordButton.jsx
  src/components/Button/SignInButton.jsx
  src/components/Card/Chart/PeriodPostCountCard.jsx
  src/components/Card/Chart/TodayPostCountCard.jsx
  src/components/Card/Post/PostCard.jsx
  src/components/Card/Post/PostCardList.jsx
  src/components/Card/UserGroup/UserGroupCard.jsx
  src/components/Card/UserGroup/UserGroupCardList.jsx
  src/components/Chip/AdChip.jsx
  src/components/Common/Logo.jsx
  src/components/DropDown/SelectGroupDropDown.jsx
  src/components/DropDown/SelectGroupOptionList.jsx
  src/components/Header/DashboardHeader.jsx
  src/components/Icon/CalendarIcon.jsx
  src/components/Icon/DownwardArrowIcon.jsx
  src/components/Icon/EndashIcon.jsx
  src/components/Icon/LeftCarouselIcon.jsx
  src/components/Icon/ProfileIcon.jsx
  src/components/Icon/RightCarouselIcon.jsx
  src/components/Icon/UpdateIcon.jsx
  src/components/Icon/UpwardArrowIcon.jsx
  src/components/Layout/Footer.jsx
  src/components/Layout/Header.jsx
  src/components/Modal/CreateKeywordModal.jsx
  src/components/Modal/ModalFrame.jsx
  src/components/Pagination/PeriodPagination.jsx
  src/components/Sidebar/DashboardSidebar.jsx
  src/components/Sidebar/MyPageSidebar.jsx
  src/config/constants.js
  src/pages/GroupPage.jsx
  src/pages/HomePage.jsx
  src/pages/KeywordPage.jsx
  src/store/client/authSlice.js
  src/store/client/userDataSlice.js
  src/utils/sanitizeHtmlEntity.js
  tailwind.config.js
Labels: ✏ fix, ✨ feat, 🎨 style, 📣 code review

#29 Feat: 그룹 대시보드 게시물 수, 좋아요 수, 댓글 수 차트 구현
  src/api/group/asyncGetGroupCommentCountList.js
  src/api/group/asyncGetGroupLikeCountList.js
  src/api/group/asyncGetGroupPostCountList.js
  src/components/Card/Chart/GroupPeriodPostCountCard.jsx
  src/components/Card/Chart/TodayPostCountCard.jsx
  src/components/Chart/GroupLineChart.jsx
  src/components/Modal/ErrorModal.jsx
  src/components/Pagination/GroupPeriodPagination.jsx
  src/components/Pagination/PeriodPagination.jsx
  src/components/UI/Error.jsx
  src/config/constants.js
  src/pages/GroupPage.jsx
Labels: ✨ feat, 🎨 style, 📣 code review

#36 Fix: Query가 invalidate 되지 않는 이슈 해결 및 키워드 대시보드 스타일 수정
  src/components/Card/Chart/GroupPeriodPostCountCard.jsx
  src/components/Card/Chart/PeriodPostCommentCard.jsx
  src/components/Card/Chart/PeriodPostCountCard.jsx
  src/components/Card/Chart/PeriodPostLikeCard.jsx
  src/components/Card/Chart/TodayPostCountCard.jsx
  src/components/Card/Post/PostCardList.jsx
  src/components/Modal/CreateKeywordModal.jsx
  src/config/constants.js
  src/pages/GroupPage.jsx
  src/pages/KeywordPage.jsx
Labels: ✏ fix, 🎨 style, 📣 code review

#44 Style: 전반적인 UI 수정
  src/components/Button/PeriodToggleButton.jsx
  src/components/Button/SignInButton.jsx
  src/components/Card/Chart/GroupPeriodPostCountCard.jsx
  src/components/Card/Chart/PeriodAdCountCard.jsx
  src/components/Card/Chart/PeriodPostCountCard.jsx
  src/components/Card/Chart/PeriodReactionCountCard.jsx
  src/components/Card/Chart/TodayPostCountCard.jsx
  src/components/Card/Post/PostCard.jsx
  src/components/Card/Post/PostListFilter.jsx
  src/components/Card/UserGroup/UserGroupCard.jsx
  src/components/Card/UserGroup/UserGroupCardList.jsx
  src/components/Chart/GroupLineChart.jsx
  src/components/Chart/LineChart.jsx
  src/components/Chart/MultiTypeChart.jsx
  src/components/Chart/StackBarChart.jsx
  src/components/Header/DashboardHeader.jsx
  src/components/Icon/CalendarIcon.jsx
  src/components/Icon/ChartIcon.jsx
  src/components/Icon/CommentIcon.jsx
  src/components/Icon/DownwardArrowIcon.jsx
  src/components/Icon/HashtagIcon.jsx
  src/components/Icon/LikeIcon.jsx
  src/components/Icon/PostIcon.jsx
  src/components/Icon/ProfileIcon.jsx
  src/components/Icon/ResetIcon.jsx
  src/components/Icon/SignOutIcon.jsx
  src/components/Icon/UpdateIcon.jsx
  src/components/Layout/Header.jsx
  src/components/Pagination/GroupPeriodPagination.jsx
  src/components/Pagination/PeriodPagination.jsx
  src/components/Sidebar/DashboardSidebar.jsx
  src/components/Sidebar/MyPageSidebar.jsx
  src/config/constants.js
  src/pages/KeywordPage.jsx
Labels: 🎨 style, 🔨 refactor

#48 Feat: 그룹 이름 변경 UI
  src/api/group/asyncPutGroupName.js
  src/components/Button/SignInButton.jsx
  src/components/Header/DashboardHeader.jsx
  src/config/constants.js
  src/pages/GroupPage.jsx
Labels: ✨ feat, 📣 code review

#50 Feat: 키워드 구독 해지 UI 구현
  src/api/keyword/asyncDeleteKeyword.js
  src/components/Header/DashboardHeader.jsx
  src/components/Modal/AlertModal.jsx
  src/components/Modal/ConfirmModal.jsx
  src/config/constants.js
  src/pages/KeywordPage.jsx
Labels: ✨ feat, 📣 code review

#51 Feat: 스켈레톤 UI, 랜딩 페이지 및 메타데이터 구현
  .nvmrc
  index.html
  netlify.toml
  public/_redirects
  public/assets/bloblow_og_image.png
  public/assets/groupChartSample.png
  public/assets/postListSample.png
  public/favicon.png
  src/components/Button/SignInButton.jsx
  src/components/Card/Chart/GroupPeriodPostCountCard.jsx
  src/components/Card/Chart/PeriodAdCountCard.jsx
  src/components/Card/Chart/PeriodPostCountCard.jsx
  src/components/Card/Chart/PeriodReactionCountCard.jsx
  src/components/Card/Chart/TodayPostCountCard.jsx
  src/components/Card/Post/PostCardList.jsx
  src/components/Header/DashboardHeader.jsx
  src/components/Icon/EmailIcon.jsx
  src/components/Icon/GithubIcon.jsx
  src/components/Layout/Footer.jsx
  src/components/Layout/Header.jsx
  src/components/Modal/CreateKeywordSuccessModal.jsx
  src/components/Modal/ErrorModal.jsx
  src/components/Sidebar/DashboardSidebar.jsx
  src/components/UI/ChartSkeleton.jsx
  src/components/UI/Error.jsx
  src/config/ReactQueryProvider.jsx
  src/config/constants.js
  src/pages/App.jsx
  src/pages/GroupPage.jsx
  src/pages/HomePage.jsx
  src/pages/KeywordPage.jsx
  src/pages/NotFoundPage.jsx
  tailwind.config.js
Labels: ✨ feat, 🎨 style, 📣 code review, 🔨 refactor

#55 Fix: 구독 해지 버튼 원복
  src/components/Header/DashboardHeader.jsx
Labels: ✏ fix
